services:
  db:
    build: ./mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
      
  adminer:
    image: adminer
    ports:
      - "8080:8080"
    depends_on:
      - db